site:
  name: pmsGo #站点名称
  maintain: false #是否开启维护
  debug: true
  port: 8080
  cors: true

database:
  host: 127.0.0.1:3306
  username: homestead
  password: secret
  database: pms
  charset: utf8mb4
  prefix: pms_

redis:
  host: 127.0.0.1
  port: 6379
  auth: ""
  prefix: "pms:"

session:
  name: pms_server
  secret: qwerty
  type: redis
  idle: 10

web:
  security:
    primaryKey: "config\\rsa_1024_priv.pem"
    salt: "xcvmnbiufs"
  host: "http://web.pms.test"
  connects: [ github ]
  auth:
    admin:
      except: [ ]
      optional: [ login,auth,logout ]
  upload:
    path: "D:\\GoCode\\pmsGo\\public\\upload"
    url: "http://web.pms.test/go/public/upload"
    extensions: [ "*" ] #支持文件后缀
    maxSize: "1024M" #最大单个文件大小
    maxFiles: 10 #最大文件数量
    mimeTypes: [ "*" ] #支持文件类型