site:
  name: pmsGo #站点名称
  maintain: false #是否开启维护
  debug: true
  listen: ":8080"
  cors: true

database:
  host: "127.0.0.1:3306"
  username: homestead
  password: secret
  database: pms
  charset: utf8mb4
  prefix: pms_

redis:
  host: 127.0.0.1
  port: 6379
  auth: ""

cache:
  prefix: "pms:cache:"
  expire: 1800

session:
  name: "pms_server"
  prefix: "pms:session:"
  secret: "qwerty"
  type: "cache"
  idle: 10

log:
  file: app.log
  level: debug
  json: false

web:
  security:
    primaryKey: "config\\rsa_1024_priv.pem"
    salt: "xcvmnbiufs"
  host: "http://web.local.chinamcloud.com/"
  connects: [ alipay,github,baidu,gitee,facebook,google,line,qq,twitter,wechat,weibo]
  upload:
    path: "D:\\GoCode\\pmsGo\\public\\upload"
    url: "http://web.local.chinamcloud.com/go/public/upload"
    video:
      ffmpeg: "D:\\ffmpeg\\bin\\ffmpeg.exe" #ffmpeg bin文件地址
      ffprobe: "D:\\ffmpeg\\bin\\ffprobe.exe" #ffprobe bin文件地址
      extensions: [ "mp4" ] #支持文件后缀
      maxSize: "3096M" #最大单个文件大小
      maxFiles: 10 #最大文件数量
      mimeTypes: [ "video/mp4" ] #支持文件类型
    image:
      extensions: [ "jpg" ] #支持文件后缀
      maxSize: "1024M" #最大单个文件大小
      maxFiles: 10 #最大文件数量
      mimeTypes: [ "image/jpeg" ] #支持文件类型