site:
  name: pmsGo
  maintain: false
  debug: true
  port: 8080
  cors: true

database:
  host: 127.0.0.1
  port: 3306
  username: homestead
  password: secret
  database: pms
  charset: utf8mb4
  prefix: pms_

redis:
  host: 127.0.0.1
  port: 6379
  auth: ""
  prefix: "pms:"