site:
  name: pmsGo
  maintain: false
  debug: true
  port: 8080
  cors: true

database:
  host: 127.0.0.1:33060
  username: homestead
  password: secret
  database: pms
  charset: utf8mb4
  prefix: pms_

redis:
  host: 127.0.0.1
  port: 6379
  auth: ""
  prefix: "pms:"

session:
  name: pms_server
  secret: qwerty
  type: redis
  idle: 10

web:
  connects: [ alipay,baidu,facebook,github,google,line,twitter,qq,wechat,weibo ]
  auth:
    admin:
      except: [ ]
      optional: [ login,auth,logout ]