site:
  name: pmsGo
  maintain: false
  debug: true
  port: 8080
  cors: true

database:
  host: 127.0.0.1:33060
  username: homestead
  password: secret
  database: pms
  charset: utf8mb4
  prefix: pms_

redis:
  host: 127.0.0.1
  port: 6379
  auth: ""
  prefix: "pms:"

session:
  name: pms_server
  secret: qwerty
  type: redis
  idle: 10

web:
  connects: [ alipay,baidu,facebook,github,google,line,twitter,qq,wechat,weibo ]
  auth:
    admin:
      except: [ ]
      optional: [ login,auth,logout ]
  upload:
    path: "D:\\GoCode\\src\\pmsGo\\tmp"
    url: "http://127.0.0.1"
    extensions: [ "*" ] #支持文件后缀
    maxSize: "1024M" #最大单个文件大小
    maxFiles: 10 #最大文件数量
    mimeTypes: [ "*" ] #支持文件类型